//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;
namespace Visy.Middleware.SAP.LionNathan.Plastics.Components
{
    // 
    // This source code was auto-generated by xsd, Version=2.0.50727.42.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class VISY
    {

        private object[] itemsField;

        private ItemsChoiceType[] itemsElementNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("From", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("PurchaseOrders", typeof(PurchaseOrders))]
        [System.Xml.Serialization.XmlElementAttribute("To", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class PurchaseOrders
    {

        private PurchaseOrder[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PurchaseOrder")]
        public PurchaseOrder[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class PurchaseOrder
    {

        private object[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Details", typeof(Details))]
        [System.Xml.Serialization.XmlElementAttribute("Headers", typeof(Headers))]
        [System.Xml.Serialization.XmlElementAttribute("Texts", typeof(Texts))]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Details
    {

        private Detail[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Detail")]
        public Detail[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Detail
    {

        private string f1Field;

        private string f2Field;

        private string f3Field;

        private string f4Field;

        private string f5Field;

        private string f6Field;

        private string f7Field;

        private string f8Field;

        private string f9Field;

        private string f10Field;

        private string f11Field;

        private string f12Field;

        private string f13Field;

        private string f14Field;

        private string f15Field;

        private string f16Field;

        private string f17Field;

        private string f18Field;

        private string f19Field;

        private string f20Field;

        private string f21Field;

        private string f22Field;

        private string f23Field;

        private string f24Field;

        private string f25Field;

        private string f26Field;

        private string f27Field;

        private string f28Field;

        private string f29Field;

        private string f30Field;

        private string f31Field;

        private string f32Field;

        private string f33Field;

        private string f34Field;

        private string f35Field;

        private string f36Field;

        private string f37Field;

        private string f38Field;

        private string f39Field;

        private string f40Field;

        private string f41Field;

        private string f42Field;

        private string f43Field;

        private string f44Field;

        private string f45Field;

        private string f46Field;

        private string f47Field;

        private string f48Field;

        private string f49Field;

        private string f50Field;

        private string f51Field;

        private string f52Field;

        private string f53Field;

        private string f54Field;
        private string f55Field;
        private string f56Field;
        private string f57Field;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F1
        {
            get
            {
                return this.f1Field;
            }
            set
            {
                this.f1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F2
        {
            get
            {
                return this.f2Field;
            }
            set
            {
                this.f2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F3
        {
            get
            {
                return this.f3Field;
            }
            set
            {
                this.f3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F4
        {
            get
            {
                return this.f4Field;
            }
            set
            {
                this.f4Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F5
        {
            get
            {
                return this.f5Field;
            }
            set
            {
                this.f5Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F6
        {
            get
            {
                return this.f6Field;
            }
            set
            {
                this.f6Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F7
        {
            get
            {
                return this.f7Field;
            }
            set
            {
                this.f7Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F8
        {
            get
            {
                return this.f8Field;
            }
            set
            {
                this.f8Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F9
        {
            get
            {
                return this.f9Field;
            }
            set
            {
                this.f9Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F10
        {
            get
            {
                return this.f10Field;
            }
            set
            {
                this.f10Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F11
        {
            get
            {
                return this.f11Field;
            }
            set
            {
                this.f11Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F12
        {
            get
            {
                return this.f12Field;
            }
            set
            {
                this.f12Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F13
        {
            get
            {
                return this.f13Field;
            }
            set
            {
                this.f13Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F14
        {
            get
            {
                return this.f14Field;
            }
            set
            {
                this.f14Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F15
        {
            get
            {
                return this.f15Field;
            }
            set
            {
                this.f15Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F16
        {
            get
            {
                return this.f16Field;
            }
            set
            {
                this.f16Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F17
        {
            get
            {
                return this.f17Field;
            }
            set
            {
                this.f17Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F18
        {
            get
            {
                return this.f18Field;
            }
            set
            {
                this.f18Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F19
        {
            get
            {
                return this.f19Field;
            }
            set
            {
                this.f19Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F20
        {
            get
            {
                return this.f20Field;
            }
            set
            {
                this.f20Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F21
        {
            get
            {
                return this.f21Field;
            }
            set
            {
                this.f21Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F22
        {
            get
            {
                return this.f22Field;
            }
            set
            {
                this.f22Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F23
        {
            get
            {
                return this.f23Field;
            }
            set
            {
                this.f23Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F24
        {
            get
            {
                return this.f24Field;
            }
            set
            {
                this.f24Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F25
        {
            get
            {
                return this.f25Field;
            }
            set
            {
                this.f25Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F26
        {
            get
            {
                return this.f26Field;
            }
            set
            {
                this.f26Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F27
        {
            get
            {
                return this.f27Field;
            }
            set
            {
                this.f27Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F28
        {
            get
            {
                return this.f28Field;
            }
            set
            {
                this.f28Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F29
        {
            get
            {
                return this.f29Field;
            }
            set
            {
                this.f29Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F30
        {
            get
            {
                return this.f30Field;
            }
            set
            {
                this.f30Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F31
        {
            get
            {
                return this.f31Field;
            }
            set
            {
                this.f31Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F32
        {
            get
            {
                return this.f32Field;
            }
            set
            {
                this.f32Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F33
        {
            get
            {
                return this.f33Field;
            }
            set
            {
                this.f33Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F34
        {
            get
            {
                return this.f34Field;
            }
            set
            {
                this.f34Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F35
        {
            get
            {
                return this.f35Field;
            }
            set
            {
                this.f35Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F36
        {
            get
            {
                return this.f36Field;
            }
            set
            {
                this.f36Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F37
        {
            get
            {
                return this.f37Field;
            }
            set
            {
                this.f37Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F38
        {
            get
            {
                return this.f38Field;
            }
            set
            {
                this.f38Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F39
        {
            get
            {
                return this.f39Field;
            }
            set
            {
                this.f39Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F40
        {
            get
            {
                return this.f40Field;
            }
            set
            {
                this.f40Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F41
        {
            get
            {
                return this.f41Field;
            }
            set
            {
                this.f41Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F42
        {
            get
            {
                return this.f42Field;
            }
            set
            {
                this.f42Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F43
        {
            get
            {
                return this.f43Field;
            }
            set
            {
                this.f43Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F44
        {
            get
            {
                return this.f44Field;
            }
            set
            {
                this.f44Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F45
        {
            get
            {
                return this.f45Field;
            }
            set
            {
                this.f45Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F46
        {
            get
            {
                return this.f46Field;
            }
            set
            {
                this.f46Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F47
        {
            get
            {
                return this.f47Field;
            }
            set
            {
                this.f47Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F48
        {
            get
            {
                return this.f48Field;
            }
            set
            {
                this.f48Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F49
        {
            get
            {
                return this.f49Field;
            }
            set
            {
                this.f49Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F50
        {
            get
            {
                return this.f50Field;
            }
            set
            {
                this.f50Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F51
        {
            get
            {
                return this.f51Field;
            }
            set
            {
                this.f51Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F52
        {
            get
            {
                return this.f52Field;
            }
            set
            {
                this.f52Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F53
        {
            get
            {
                return this.f53Field;
            }
            set
            {
                this.f53Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F54
        {
            get
            {
                return this.f54Field;
            }
            set
            {
                this.f54Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F55
        {
            get
            {
                return this.f55Field;
            }
            set
            {
                this.f55Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F56
        {
            get
            {
                return this.f56Field;
            }
            set
            {
                this.f56Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F57
        {
            get
            {
                return this.f57Field;
            }
            set
            {
                this.f57Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Headers
    {

        private Header[] itemsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Header")]
        public Header[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Header
    {

        private string f1Field;

        private string f2Field;

        private string f3Field;

        private string f4Field;

        private string f5Field;

        private string f6Field;

        private string f7Field;

        private string f8Field;

        private string f9Field;

        private string f10Field;

        private string f11Field;

        private string f12Field;

        private string f13Field;

        private string f14Field;

        private string f15Field;

        private string f16Field;

        private string f17Field;

        private string f18Field;

        private string f19Field;

        private string f20Field;

        private string f21Field;

        private string f22Field;

        private string f23Field;

        private string f24Field;

        private string f25Field;

        private string f26Field;

        private string f27Field;

        private string f28Field;

        private string f29Field;

        private string f30Field;

        private string f31Field;

        private string f32Field;

        private string f33Field;

        private string f34Field;

        private string f35Field;

        private string f36Field;

        private string f37Field;

        private string f38Field;

        private string f39Field;

        private string f40Field;

        private string f41Field;

        private string f42Field;

        private string f43Field;

        private string f44Field;

        private string f45Field;

        private string f46Field;

        private string f47Field;

        private string f48Field;

        private string f49Field;

        private string f50Field;

        private string f51Field;

        private string f52Field;

        private string f53Field;

        private string f54Field;

        private string valueField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F1
        {
            get
            {
                return this.f1Field;
            }
            set
            {
                this.f1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F2
        {
            get
            {
                return this.f2Field;
            }
            set
            {
                this.f2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F3
        {
            get
            {
                return this.f3Field;
            }
            set
            {
                this.f3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F4
        {
            get
            {
                return this.f4Field;
            }
            set
            {
                this.f4Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F5
        {
            get
            {
                return this.f5Field;
            }
            set
            {
                this.f5Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F6
        {
            get
            {
                return this.f6Field;
            }
            set
            {
                this.f6Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F7
        {
            get
            {
                return this.f7Field;
            }
            set
            {
                this.f7Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F8
        {
            get
            {
                return this.f8Field;
            }
            set
            {
                this.f8Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F9
        {
            get
            {
                return this.f9Field;
            }
            set
            {
                this.f9Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F10
        {
            get
            {
                return this.f10Field;
            }
            set
            {
                this.f10Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F11
        {
            get
            {
                return this.f11Field;
            }
            set
            {
                this.f11Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F12
        {
            get
            {
                return this.f12Field;
            }
            set
            {
                this.f12Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F13
        {
            get
            {
                return this.f13Field;
            }
            set
            {
                this.f13Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F14
        {
            get
            {
                return this.f14Field;
            }
            set
            {
                this.f14Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F15
        {
            get
            {
                return this.f15Field;
            }
            set
            {
                this.f15Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F16
        {
            get
            {
                return this.f16Field;
            }
            set
            {
                this.f16Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F17
        {
            get
            {
                return this.f17Field;
            }
            set
            {
                this.f17Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F18
        {
            get
            {
                return this.f18Field;
            }
            set
            {
                this.f18Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F19
        {
            get
            {
                return this.f19Field;
            }
            set
            {
                this.f19Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F20
        {
            get
            {
                return this.f20Field;
            }
            set
            {
                this.f20Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F21
        {
            get
            {
                return this.f21Field;
            }
            set
            {
                this.f21Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F22
        {
            get
            {
                return this.f22Field;
            }
            set
            {
                this.f22Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F23
        {
            get
            {
                return this.f23Field;
            }
            set
            {
                this.f23Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F24
        {
            get
            {
                return this.f24Field;
            }
            set
            {
                this.f24Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F25
        {
            get
            {
                return this.f25Field;
            }
            set
            {
                this.f25Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F26
        {
            get
            {
                return this.f26Field;
            }
            set
            {
                this.f26Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F27
        {
            get
            {
                return this.f27Field;
            }
            set
            {
                this.f27Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F28
        {
            get
            {
                return this.f28Field;
            }
            set
            {
                this.f28Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F29
        {
            get
            {
                return this.f29Field;
            }
            set
            {
                this.f29Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F30
        {
            get
            {
                return this.f30Field;
            }
            set
            {
                this.f30Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F31
        {
            get
            {
                return this.f31Field;
            }
            set
            {
                this.f31Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F32
        {
            get
            {
                return this.f32Field;
            }
            set
            {
                this.f32Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F33
        {
            get
            {
                return this.f33Field;
            }
            set
            {
                this.f33Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F34
        {
            get
            {
                return this.f34Field;
            }
            set
            {
                this.f34Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F35
        {
            get
            {
                return this.f35Field;
            }
            set
            {
                this.f35Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F36
        {
            get
            {
                return this.f36Field;
            }
            set
            {
                this.f36Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F37
        {
            get
            {
                return this.f37Field;
            }
            set
            {
                this.f37Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F38
        {
            get
            {
                return this.f38Field;
            }
            set
            {
                this.f38Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F39
        {
            get
            {
                return this.f39Field;
            }
            set
            {
                this.f39Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F40
        {
            get
            {
                return this.f40Field;
            }
            set
            {
                this.f40Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F41
        {
            get
            {
                return this.f41Field;
            }
            set
            {
                this.f41Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F42
        {
            get
            {
                return this.f42Field;
            }
            set
            {
                this.f42Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F43
        {
            get
            {
                return this.f43Field;
            }
            set
            {
                this.f43Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F44
        {
            get
            {
                return this.f44Field;
            }
            set
            {
                this.f44Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F45
        {
            get
            {
                return this.f45Field;
            }
            set
            {
                this.f45Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F46
        {
            get
            {
                return this.f46Field;
            }
            set
            {
                this.f46Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F47
        {
            get
            {
                return this.f47Field;
            }
            set
            {
                this.f47Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F48
        {
            get
            {
                return this.f48Field;
            }
            set
            {
                this.f48Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F49
        {
            get
            {
                return this.f49Field;
            }
            set
            {
                this.f49Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F50
        {
            get
            {
                return this.f50Field;
            }
            set
            {
                this.f50Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F51
        {
            get
            {
                return this.f51Field;
            }
            set
            {
                this.f51Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F52
        {
            get
            {
                return this.f52Field;
            }
            set
            {
                this.f52Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F53
        {
            get
            {
                return this.f53Field;
            }
            set
            {
                this.f53Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F54
        {
            get
            {
                return this.f54Field;
            }
            set
            {
                this.f54Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Texts
    {

        private Text textField;

        /// <remarks/>
        public Text Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class Text
    {

        private string f1Field;

        private string f2Field;

        private string f3Field;

        private string f4Field;

        private string f5Field;

        private string f6Field;

        private string f7Field;

        private string f8Field;

        private string f9Field;

        private string f10Field;

        private string f11Field;

        private string f12Field;

        private string f13Field;

        private string f14Field;

        private string f15Field;

        private string f16Field;

        private string f17Field;

        private string f18Field;

        private string f19Field;

        private string f20Field;

        private string f21Field;

        private string f22Field;

        private string f23Field;

        private string f24Field;

        private string f25Field;

        private string f26Field;

        private string f27Field;

        private string f28Field;

        private string f29Field;

        private string f30Field;

        private string f31Field;

        private string f32Field;

        private string f33Field;

        private string f34Field;

        private string f35Field;

        private string f36Field;

        private string f37Field;

        private string f38Field;

        private string f39Field;

        private string f40Field;

        private string f41Field;

        private string f42Field;

        private string f43Field;

        private string f44Field;

        private string f45Field;

        private string f46Field;

        private string f47Field;

        private string f48Field;

        private string f49Field;

        private string f50Field;

        private string f51Field;

        private string f52Field;

        private string f53Field;

        private string f54Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F1
        {
            get
            {
                return this.f1Field;
            }
            set
            {
                this.f1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F2
        {
            get
            {
                return this.f2Field;
            }
            set
            {
                this.f2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F3
        {
            get
            {
                return this.f3Field;
            }
            set
            {
                this.f3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F4
        {
            get
            {
                return this.f4Field;
            }
            set
            {
                this.f4Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F5
        {
            get
            {
                return this.f5Field;
            }
            set
            {
                this.f5Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F6
        {
            get
            {
                return this.f6Field;
            }
            set
            {
                this.f6Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F7
        {
            get
            {
                return this.f7Field;
            }
            set
            {
                this.f7Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F8
        {
            get
            {
                return this.f8Field;
            }
            set
            {
                this.f8Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F9
        {
            get
            {
                return this.f9Field;
            }
            set
            {
                this.f9Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F10
        {
            get
            {
                return this.f10Field;
            }
            set
            {
                this.f10Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F11
        {
            get
            {
                return this.f11Field;
            }
            set
            {
                this.f11Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F12
        {
            get
            {
                return this.f12Field;
            }
            set
            {
                this.f12Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F13
        {
            get
            {
                return this.f13Field;
            }
            set
            {
                this.f13Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F14
        {
            get
            {
                return this.f14Field;
            }
            set
            {
                this.f14Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F15
        {
            get
            {
                return this.f15Field;
            }
            set
            {
                this.f15Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F16
        {
            get
            {
                return this.f16Field;
            }
            set
            {
                this.f16Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F17
        {
            get
            {
                return this.f17Field;
            }
            set
            {
                this.f17Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F18
        {
            get
            {
                return this.f18Field;
            }
            set
            {
                this.f18Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F19
        {
            get
            {
                return this.f19Field;
            }
            set
            {
                this.f19Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F20
        {
            get
            {
                return this.f20Field;
            }
            set
            {
                this.f20Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F21
        {
            get
            {
                return this.f21Field;
            }
            set
            {
                this.f21Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F22
        {
            get
            {
                return this.f22Field;
            }
            set
            {
                this.f22Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F23
        {
            get
            {
                return this.f23Field;
            }
            set
            {
                this.f23Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F24
        {
            get
            {
                return this.f24Field;
            }
            set
            {
                this.f24Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F25
        {
            get
            {
                return this.f25Field;
            }
            set
            {
                this.f25Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F26
        {
            get
            {
                return this.f26Field;
            }
            set
            {
                this.f26Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F27
        {
            get
            {
                return this.f27Field;
            }
            set
            {
                this.f27Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F28
        {
            get
            {
                return this.f28Field;
            }
            set
            {
                this.f28Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F29
        {
            get
            {
                return this.f29Field;
            }
            set
            {
                this.f29Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F30
        {
            get
            {
                return this.f30Field;
            }
            set
            {
                this.f30Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F31
        {
            get
            {
                return this.f31Field;
            }
            set
            {
                this.f31Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F32
        {
            get
            {
                return this.f32Field;
            }
            set
            {
                this.f32Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F33
        {
            get
            {
                return this.f33Field;
            }
            set
            {
                this.f33Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F34
        {
            get
            {
                return this.f34Field;
            }
            set
            {
                this.f34Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F35
        {
            get
            {
                return this.f35Field;
            }
            set
            {
                this.f35Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F36
        {
            get
            {
                return this.f36Field;
            }
            set
            {
                this.f36Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F37
        {
            get
            {
                return this.f37Field;
            }
            set
            {
                this.f37Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F38
        {
            get
            {
                return this.f38Field;
            }
            set
            {
                this.f38Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F39
        {
            get
            {
                return this.f39Field;
            }
            set
            {
                this.f39Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F40
        {
            get
            {
                return this.f40Field;
            }
            set
            {
                this.f40Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F41
        {
            get
            {
                return this.f41Field;
            }
            set
            {
                this.f41Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F42
        {
            get
            {
                return this.f42Field;
            }
            set
            {
                this.f42Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F43
        {
            get
            {
                return this.f43Field;
            }
            set
            {
                this.f43Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F44
        {
            get
            {
                return this.f44Field;
            }
            set
            {
                this.f44Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F45
        {
            get
            {
                return this.f45Field;
            }
            set
            {
                this.f45Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F46
        {
            get
            {
                return this.f46Field;
            }
            set
            {
                this.f46Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F47
        {
            get
            {
                return this.f47Field;
            }
            set
            {
                this.f47Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F48
        {
            get
            {
                return this.f48Field;
            }
            set
            {
                this.f48Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F49
        {
            get
            {
                return this.f49Field;
            }
            set
            {
                this.f49Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F50
        {
            get
            {
                return this.f50Field;
            }
            set
            {
                this.f50Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F51
        {
            get
            {
                return this.f51Field;
            }
            set
            {
                this.f51Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F52
        {
            get
            {
                return this.f52Field;
            }
            set
            {
                this.f52Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F53
        {
            get
            {
                return this.f53Field;
            }
            set
            {
                this.f53Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string F54
        {
            get
            {
                return this.f54Field;
            }
            set
            {
                this.f54Field = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema = false)]
    public enum ItemsChoiceType
    {

        /// <remarks/>
        From,

        /// <remarks/>
        PurchaseOrders,

        /// <remarks/>
        To,
    }
}
