//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3623
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
namespace Visy.Middleware.SAP.LionNathan.Plastics.Components
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://SAP.LIONNATHAN.PLASTICS.SingleDELFOR")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://SAP.LIONNATHAN.PLASTICS.SingleDELFOR", IsNullable = false)]
    public partial class SingleDELFOR
    {

        private string plantCodeField;

        private SingleDELFORDate[] dateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PlantCode
        {
            get
            {
                return this.plantCodeField;
            }
            set
            {
                this.plantCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Date", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SingleDELFORDate[] Date
        {
            get
            {
                return this.dateField;
            }
            set
            {
                this.dateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://SAP.LIONNATHAN.PLASTICS.SingleDELFOR")]
    public partial class SingleDELFORDate
    {

        private string date1Field;

        private string date2Field;

        private string date3Field;

        private string date4Field;

        private string date5Field;

        private string date6Field;

        private string date7Field;

        private string date8Field;

        private string date9Field;

        private string date10Field;

        private string date11Field;

        private string date12Field;

        private string date13Field;

        private string date14Field;

        private string date15Field;

        private string date16Field;

        private string date17Field;

        private string date18Field;

        private string date19Field;

        private string date20Field;

        private string date21Field;

        private string date22Field;

        private string date23Field;

        private string date24Field;

        private string date25Field;

        private string date26Field;

        private string date27Field;

        private string date28Field;

        private string date29Field;
        private string date30Field;
        private string date31Field;
        private string date32Field;
        private string date33Field;
        private string date34Field;
        private string date35Field;
        private string date36Field;
        private string date37Field;
        private string date38Field;
        private string date39Field;
        private string date40Field;
        private string date41Field;
        private string date42Field;
        private string date43Field;
        private string date44Field;
        private string date45Field;
        private string date46Field;
        private string date47Field;
        private string date48Field;
        private string date49Field;
        private string date50Field;
        private string date51Field;
        private string date52Field;

        private SingleDELFORDateBatchItem[] batchItemField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date1
        {
            get
            {
                return this.date1Field;
            }
            set
            {
                this.date1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date2
        {
            get
            {
                return this.date2Field;
            }
            set
            {
                this.date2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date3
        {
            get
            {
                return this.date3Field;
            }
            set
            {
                this.date3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date4
        {
            get
            {
                return this.date4Field;
            }
            set
            {
                this.date4Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date5
        {
            get
            {
                return this.date5Field;
            }
            set
            {
                this.date5Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date6
        {
            get
            {
                return this.date6Field;
            }
            set
            {
                this.date6Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date7
        {
            get
            {
                return this.date7Field;
            }
            set
            {
                this.date7Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date8
        {
            get
            {
                return this.date8Field;
            }
            set
            {
                this.date8Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date9
        {
            get
            {
                return this.date9Field;
            }
            set
            {
                this.date9Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date10
        {
            get
            {
                return this.date10Field;
            }
            set
            {
                this.date10Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date11
        {
            get
            {
                return this.date11Field;
            }
            set
            {
                this.date11Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date12
        {
            get
            {
                return this.date12Field;
            }
            set
            {
                this.date12Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date13
        {
            get
            {
                return this.date13Field;
            }
            set
            {
                this.date13Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date14
        {
            get
            {
                return this.date14Field;
            }
            set
            {
                this.date14Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date15
        {
            get
            {
                return this.date15Field;
            }
            set
            {
                this.date15Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date16
        {
            get
            {
                return this.date16Field;
            }
            set
            {
                this.date16Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date17
        {
            get
            {
                return this.date17Field;
            }
            set
            {
                this.date17Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date18
        {
            get
            {
                return this.date18Field;
            }
            set
            {
                this.date18Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date19
        {
            get
            {
                return this.date19Field;
            }
            set
            {
                this.date19Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date20
        {
            get
            {
                return this.date20Field;
            }
            set
            {
                this.date20Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date21
        {
            get
            {
                return this.date21Field;
            }
            set
            {
                this.date21Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date22
        {
            get
            {
                return this.date22Field;
            }
            set
            {
                this.date22Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date23
        {
            get
            {
                return this.date23Field;
            }
            set
            {
                this.date23Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date24
        {
            get
            {
                return this.date24Field;
            }
            set
            {
                this.date24Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date25
        {
            get
            {
                return this.date25Field;
            }
            set
            {
                this.date25Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date26
        {
            get
            {
                return this.date26Field;
            }
            set
            {
                this.date26Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date27
        {
            get
            {
                return this.date27Field;
            }
            set
            {
                this.date27Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date28
        {
            get
            {
                return this.date28Field;
            }
            set
            {
                this.date28Field = value;
            }
        }


        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date29
        {
            get
            {
                return this.date29Field;
            }
            set
            {
                this.date29Field = value;
            }
        }


        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date30
        {
            get
            {
                return this.date30Field;
            }
            set
            {
                this.date30Field = value;
            }
        }


        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date31
        {
            get
            {
                return this.date31Field;
            }
            set
            {
                this.date31Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date32
        {
            get
            {
                return this.date32Field;
            }
            set
            {
                this.date32Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date33
        {
            get
            {
                return this.date33Field;
            }
            set
            {
                this.date33Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date34
        {
            get
            {
                return this.date34Field;
            }
            set
            {
                this.date34Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date35
        {
            get
            {
                return this.date35Field;
            }
            set
            {
                this.date35Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date36        {
            get
            {
                return this.date36Field;
            }
            set
            {
                this.date36Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date37
        {
            get
            {
                return this.date37Field;
            }
            set
            {
                this.date37Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date38
        {
            get
            {
                return this.date38Field;
            }
            set
            {
                this.date38Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date39
        {
            get
            {
                return this.date39Field;
            }
            set
            {
                this.date39Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date40
        {
            get
            {
                return this.date40Field;
            }
            set
            {
                this.date40Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date41
        {
            get
            {
                return this.date41Field;
            }
            set
            {
                this.date41Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date42
        {
            get
            {
                return this.date42Field;
            }
            set
            {
                this.date42Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date43
        {
            get
            {
                return this.date43Field;
            }
            set
            {
                this.date43Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date44
        {
            get
            {
                return this.date44Field;
            }
            set
            {
                this.date44Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date45
        {
            get
            {
                return this.date45Field;
            }
            set
            {
                this.date45Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date46
        {
            get
            {
                return this.date46Field;
            }
            set
            {
                this.date46Field = value;
            }
        }


        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date47
        {
            get
            {
                return this.date47Field;
            }
            set
            {
                this.date47Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date48
        {
            get
            {
                return this.date48Field;
            }
            set
            {
                this.date48Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date49
        {
            get
            {
                return this.date49Field;
            }
            set
            {
                this.date49Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date50
        {
            get
            {
                return this.date50Field;
            }
            set
            {
                this.date50Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date51
        {
            get
            {
                return this.date51Field;
            }
            set
            {
                this.date51Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Date52
        {
            get
            {
                return this.date52Field;
            }
            set
            {
                this.date52Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BatchItem", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SingleDELFORDateBatchItem[] BatchItem
        {
            get
            {
                return this.batchItemField;
            }
            set
            {
                this.batchItemField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://SAP.LIONNATHAN.PLASTICS.SingleDELFOR")]
    public partial class SingleDELFORDateBatchItem
    {

        private string materialCodeField;

        private string materialDescField;

        private string vendorField;

        private string uOMField;

        private string qTY1Field;

        private string qTY2Field;

        private string qTY3Field;

        private string qTY4Field;

        private string qTY5Field;

        private string qTY6Field;

        private string qTY7Field;

        private string qTY8Field;

        private string qTY9Field;

        private string qTY10Field;

        private string qTY11Field;

        private string qTY12Field;

        private string qTY13Field;

        private string qTY14Field;

        private string qTY15Field;

        private string qTY16Field;

        private string qTY17Field;

        private string qTY18Field;

        private string qTY19Field;

        private string qTY20Field;

        private string qTY21Field;

        private string qTY22Field;

        private string qTY23Field;

        private string qTY24Field;

        private string qTY25Field;

        private string qTY26Field;

        private string qTY27Field;

        private string qTY28Field;
        private string qTY29Field;
        private string qTY30Field;
        private string qTY31Field;
        private string qTY32Field;
        private string qTY33Field;
        private string qTY34Field;
        private string qTY35Field;
        private string qTY36Field;
        private string qTY37Field;
        private string qTY38Field;
        private string qTY39Field;
        private string qTY40Field;
        private string qTY41Field;
        private string qTY42Field;
        private string qTY43Field;
        private string qTY44Field;
        private string qTY45Field;
        private string qTY46Field;
        private string qTY47Field;
        private string qTY48Field;
        private string qTY49Field;
        private string qTY50Field;
        private string qTY51Field;
        private string qTY52Field;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MaterialCode
        {
            get
            {
                return this.materialCodeField;
            }
            set
            {
                this.materialCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MaterialDesc
        {
            get
            {
                return this.materialDescField;
            }
            set
            {
                this.materialDescField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Vendor
        {
            get
            {
                return this.vendorField;
            }
            set
            {
                this.vendorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UOM
        {
            get
            {
                return this.uOMField;
            }
            set
            {
                this.uOMField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY1
        {
            get
            {
                return this.qTY1Field;
            }
            set
            {
                this.qTY1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY2
        {
            get
            {
                return this.qTY2Field;
            }
            set
            {
                this.qTY2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY3
        {
            get
            {
                return this.qTY3Field;
            }
            set
            {
                this.qTY3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY4
        {
            get
            {
                return this.qTY4Field;
            }
            set
            {
                this.qTY4Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY5
        {
            get
            {
                return this.qTY5Field;
            }
            set
            {
                this.qTY5Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY6
        {
            get
            {
                return this.qTY6Field;
            }
            set
            {
                this.qTY6Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY7
        {
            get
            {
                return this.qTY7Field;
            }
            set
            {
                this.qTY7Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY8
        {
            get
            {
                return this.qTY8Field;
            }
            set
            {
                this.qTY8Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY9
        {
            get
            {
                return this.qTY9Field;
            }
            set
            {
                this.qTY9Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY10
        {
            get
            {
                return this.qTY10Field;
            }
            set
            {
                this.qTY10Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY11
        {
            get
            {
                return this.qTY11Field;
            }
            set
            {
                this.qTY11Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY12
        {
            get
            {
                return this.qTY12Field;
            }
            set
            {
                this.qTY12Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY13
        {
            get
            {
                return this.qTY13Field;
            }
            set
            {
                this.qTY13Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY14
        {
            get
            {
                return this.qTY14Field;
            }
            set
            {
                this.qTY14Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY15
        {
            get
            {
                return this.qTY15Field;
            }
            set
            {
                this.qTY15Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY16
        {
            get
            {
                return this.qTY16Field;
            }
            set
            {
                this.qTY16Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY17
        {
            get
            {
                return this.qTY17Field;
            }
            set
            {
                this.qTY17Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY18
        {
            get
            {
                return this.qTY18Field;
            }
            set
            {
                this.qTY18Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY19
        {
            get
            {
                return this.qTY19Field;
            }
            set
            {
                this.qTY19Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY20
        {
            get
            {
                return this.qTY20Field;
            }
            set
            {
                this.qTY20Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY21
        {
            get
            {
                return this.qTY21Field;
            }
            set
            {
                this.qTY21Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY22
        {
            get
            {
                return this.qTY22Field;
            }
            set
            {
                this.qTY22Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY23
        {
            get
            {
                return this.qTY23Field;
            }
            set
            {
                this.qTY23Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY24
        {
            get
            {
                return this.qTY24Field;
            }
            set
            {
                this.qTY24Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY25
        {
            get
            {
                return this.qTY25Field;
            }
            set
            {
                this.qTY25Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY26
        {
            get
            {
                return this.qTY26Field;
            }
            set
            {
                this.qTY26Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY27
        {
            get
            {
                return this.qTY27Field;
            }
            set
            {
                this.qTY27Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY28
        {
            get
            {
                return this.qTY28Field;
            }
            set
            {
                this.qTY28Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY29
        {
            get
            {
                return this.qTY29Field;
            }
            set
            {
                this.qTY29Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY30
        {
            get
            {
                return this.qTY30Field;
            }
            set
            {
                this.qTY30Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY31
        {
            get
            {
                return this.qTY31Field;
            }
            set
            {
                this.qTY31Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY32
        {
            get
            {
                return this.qTY32Field;
            }
            set
            {
                this.qTY32Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY33
        {
            get
            {
                return this.qTY33Field;
            }
            set
            {
                this.qTY33Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY34
        {
            get
            {
                return this.qTY34Field;
            }
            set
            {
                this.qTY34Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY35
        {
            get
            {
                return this.qTY35Field;
            }
            set
            {
                this.qTY35Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY36
        {
            get
            {
                return this.qTY36Field;
            }
            set
            {
                this.qTY36Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY37
        {
            get
            {
                return this.qTY37Field;
            }
            set
            {
                this.qTY37Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY38
        {
            get
            {
                return this.qTY38Field;
            }
            set
            {
                this.qTY38Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY39
        {
            get
            {
                return this.qTY39Field;
            }
            set
            {
                this.qTY39Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY40
        {
            get
            {
                return this.qTY40Field;
            }
            set
            {
                this.qTY40Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY41
        {
            get
            {
                return this.qTY41Field;
            }
            set
            {
                this.qTY41Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY42
        {
            get
            {
                return this.qTY42Field;
            }
            set
            {
                this.qTY42Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY43
        {
            get
            {
                return this.qTY43Field;
            }
            set
            {
                this.qTY43Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY44
        {
            get
            {
                return this.qTY44Field;
            }
            set
            {
                this.qTY44Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY45
        {
            get
            {
                return this.qTY45Field;
            }
            set
            {
                this.qTY45Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY46
        {
            get
            {
                return this.qTY46Field;
            }
            set
            {
                this.qTY46Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY47
        {
            get
            {
                return this.qTY47Field;
            }
            set
            {
                this.qTY47Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY48
        {
            get
            {
                return this.qTY48Field;
            }
            set
            {
                this.qTY48Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY49
        {
            get
            {
                return this.qTY49Field;
            }
            set
            {
                this.qTY49Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY50
        {
            get
            {
                return this.qTY50Field;
            }
            set
            {
                this.qTY50Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY51
        {
            get
            {
                return this.qTY51Field;
            }
            set
            {
                this.qTY51Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QTY52
        {
            get
            {
                return this.qTY52Field;
            }
            set
            {
                this.qTY52Field = value;
            }
        }

    }

}
