//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Visy.Middleware.SAP.LionNathan.Delfor.Schemas.Forecast")]
[System.Xml.Serialization.XmlRootAttribute(Namespace= "http://Visy.Middleware.SAP.LionNathan.Delfor.Schemas.Forecast", IsNullable=false)]
public partial class Forecast {
    
    private ForecastHeader headerField;
    
    private ForecastDetails[] detailsField;

    public void CreateDetails(int NoOfDetails)
    {
        this.Details = new ForecastDetails[NoOfDetails];
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ForecastHeader Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Details", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ForecastDetails[] Details {
        get {
            return this.detailsField;
        }
        set {
            this.detailsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Visy.ECommerce.SAP.LIONNATHAN.FORECAST.Forecast")]
public partial class ForecastHeader {
    
    private string purchaseOrderField;
    
    private string documentDateField;
    
    private string fromPeriodField;
    
    private string toPeriodField;
    
    private string buyerCodeField;
    
    private string visyBuyerCodeField;
    
    private string supplierCodeField;
    
    private string visySupplierCodeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PurchaseOrder {
        get {
            return this.purchaseOrderField;
        }
        set {
            this.purchaseOrderField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DocumentDate {
        get {
            return this.documentDateField;
        }
        set {
            this.documentDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FromPeriod {
        get {
            return this.fromPeriodField;
        }
        set {
            this.fromPeriodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ToPeriod {
        get {
            return this.toPeriodField;
        }
        set {
            this.toPeriodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string BuyerCode {
        get {
            return this.buyerCodeField;
        }
        set {
            this.buyerCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string VisyBuyerCode {
        get {
            return this.visyBuyerCodeField;
        }
        set {
            this.visyBuyerCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SupplierCode {
        get {
            return this.supplierCodeField;
        }
        set {
            this.supplierCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string VisySupplierCode {
        get {
            return this.visySupplierCodeField;
        }
        set {
            this.visySupplierCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Visy.ECommerce.SAP.LIONNATHAN.FORECAST.Forecast")]
public partial class ForecastDetails {
    
    private ForecastDetailsSchedules[] schedulesField;
    
    private string lineNoField;
    
    private string materialField;
    
    private string materialDescriptionField;
    
    private string blanketOrderNoField;
    
    private string customerRefField;
    
    private string customerRefPeriodField;
    
    private string principalRefField;
    
    private string principalRefPeriodField;
    
    private string priorCumQuantityField;
    
    private string priorPastNetField;
    
    private string rawQuantityField;
    
    private string fabricQuantityField;
    
    private string deliveryPointField;
    
    private string visyShipToField;

    public void CreateSchedules(int NoOfSchedules)
    {
        this.Schedules = new ForecastDetailsSchedules[NoOfSchedules];
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Schedules", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ForecastDetailsSchedules[] Schedules {
        get {
            return this.schedulesField;
        }
        set {
            this.schedulesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LineNo {
        get {
            return this.lineNoField;
        }
        set {
            this.lineNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Material {
        get {
            return this.materialField;
        }
        set {
            this.materialField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string MaterialDescription {
        get {
            return this.materialDescriptionField;
        }
        set {
            this.materialDescriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string BlanketOrderNo {
        get {
            return this.blanketOrderNoField;
        }
        set {
            this.blanketOrderNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CustomerRef {
        get {
            return this.customerRefField;
        }
        set {
            this.customerRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CustomerRefPeriod {
        get {
            return this.customerRefPeriodField;
        }
        set {
            this.customerRefPeriodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PrincipalRef {
        get {
            return this.principalRefField;
        }
        set {
            this.principalRefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PrincipalRefPeriod {
        get {
            return this.principalRefPeriodField;
        }
        set {
            this.principalRefPeriodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PriorCumQuantity {
        get {
            return this.priorCumQuantityField;
        }
        set {
            this.priorCumQuantityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PriorPastNet {
        get {
            return this.priorPastNetField;
        }
        set {
            this.priorPastNetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RawQuantity {
        get {
            return this.rawQuantityField;
        }
        set {
            this.rawQuantityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string FabricQuantity {
        get {
            return this.fabricQuantityField;
        }
        set {
            this.fabricQuantityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DeliveryPoint {
        get {
            return this.deliveryPointField;
        }
        set {
            this.deliveryPointField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string VisyShipTo {
        get {
            return this.visyShipToField;
        }
        set {
            this.visyShipToField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Visy.ECommerce.SAP.LIONNATHAN.FORECAST.Forecast")]
public partial class ForecastDetailsSchedules {
    
    private string quantityField;
    
    private string dateField;
    
    private string bucketField;
    
    private string deliveryPlanField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Bucket {
        get {
            return this.bucketField;
        }
        set {
            this.bucketField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DeliveryPlan {
        get {
            return this.deliveryPlanField;
        }
        set {
            this.deliveryPlanField = value;
        }
    }
}
