//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

namespace Visy.Middleware.LGX.TIM.Components
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Visy.ECommerce.TIM.Schemas/datatypes")]
    [System.Xml.Serialization.XmlRootAttribute("vendor_order", Namespace = "http://Visy.ECommerce.TIM.Schemas/datatypes", IsNullable = false)]
    public partial class vendor_order_type
    {

        private int vendor_order_idField;

        private string tim_status_codeField;

        private string tim_status_descField;

        private int parent_vendor_order_idField;

        private bool parent_vendor_order_idFieldSpecified;

        private int tim_asset_idField;

        private bool tim_asset_idFieldSpecified;

        private int asset_revision_noField;

        private bool asset_revision_noFieldSpecified;

        private string tim_asset_codeField;

        private string tim_asset_descField;

        private string tim_order_type_codeField;

        private string tim_order_type_descField;

        private string tim_vendor_codeField;

        private string tim_vendor_descField;

        private string vendor_referenceField;

        private string submitted_user_nameField;

        private System.DateTime submitted_dateField;

        private bool submitted_dateFieldSpecified;

        //private System.DateTime actual_due_dateField;
        private string actual_due_dateField;

        private bool actual_due_dateFieldSpecified;

        private System.DateTime requested_due_dateField;

        private bool requested_due_dateFieldSpecified;

        private System.DateTime original_due_dateField;

        private bool original_due_dateFieldSpecified;

        private bool is_completedField;

        private bool is_completedFieldSpecified;

        private System.DateTime completed_dateField;

        private bool completed_dateFieldSpecified;

        private bool is_under_reviewField;

        private bool is_under_reviewFieldSpecified;

        private bool is_estimate_onlyField;

        private bool is_estimate_onlyFieldSpecified;

        private decimal estimate_costField;

        private bool estimate_costFieldSpecified;

        private string rfq_codeField;

        private int workflow_idField;

        private bool workflow_idFieldSpecified;

        private string plant_codeField;

        private string plant_descField;

        private string cost_centre_codeField;

        private string cost_centre_descField;

        private string customer_codeField;

        private string customer_descField;

        private string product_codeField;

        private string product_descField;

        private int poq_product_idField;

        private bool poq_product_idFieldSpecified;

        private int product_idField;

        private bool product_idFieldSpecified;

        private int stereo_idField;

        private bool stereo_idFieldSpecified;

        private string stereo_codeField;

        private int forme_idField;

        private bool forme_idFieldSpecified;

        private string forme_codeField;

        private string board_grade_codeField;

        private string board_grade_descField;

        private string product_style_codeField;

        private string product_style_descField;

        private string closure_codeField;

        private string closure_descField;

        private string drawing_codeField;

        private int internal_length_mmField;

        private bool internal_length_mmFieldSpecified;

        private int internal_width_mmField;

        private bool internal_width_mmFieldSpecified;

        private int internal_depth_mmField;

        private bool internal_depth_mmFieldSpecified;

        private short number_upField;

        private bool number_upFieldSpecified;

        private string ink_code_1Field;

        private string ink_desc_1Field;

        private string ink_code_2Field;

        private string ink_desc_2Field;

        private string ink_code_3Field;

        private string ink_desc_3Field;

        private string ink_code_4Field;

        private string ink_desc_4Field;

        private string ink_code_5Field;

        private string ink_desc_5Field;

        private string ink_code_6Field;

        private string ink_desc_6Field;

        private string plate_type_codeField;

        private string plate_type_descField;

        private string plate_height_codeField;

        private string plate_height_descField;

        private sbyte no_of_coloursField;

        private bool no_of_coloursFieldSpecified;

        private bool is_preprintField;

        private bool is_preprintFieldSpecified;

        private bool is_proof_a3Field;

        private bool is_proof_a3FieldSpecified;

        private bool is_proof_ao_plotField;

        private bool is_proof_ao_plotFieldSpecified;

        private bool is_proof_pdfField;

        private bool is_proof_pdfFieldSpecified;

        private bool is_proof_multiupField;

        private bool is_proof_multiupFieldSpecified;

        private bool is_proof_digitalField;

        private bool is_proof_digitalFieldSpecified;

        private bool is_proof_full_deckleField;

        private bool is_proof_full_deckleFieldSpecified;

        private string screen_ruling_codeField;

        private string screen_ruling_descField;

        private string barcodeField;

        private int barcode_magnificationField;

        private bool barcode_magnificationFieldSpecified;

        private string bardesc_magnificationField;

        private string barcode_type_codeField;

        private string cylinder_repeat_codeField;

        private string cylinder_repeat_descField;

        private string artwork_method_codeField;

        private string artwork_method_descField;

        private string artwork_request_codeField;

        private string artwork_request_descField;

        private sbyte film_no_upField;

        private bool film_no_upFieldSpecified;

        private sbyte no_cartons_acrossField;

        private bool no_cartons_acrossFieldSpecified;

        private sbyte no_cartons_aroundField;

        private bool no_cartons_aroundFieldSpecified;

        private string preprint_codeField;

        private string preprint_descField;

        private string film_commentField;

        private decimal total_costField;

        private bool total_costFieldSpecified;

        //private decimal total_hoursField;
        private string total_hoursField;

        private bool total_hoursFieldSpecified;

        //private decimal sqmField;
        private string sqmField;

        private bool sqmFieldSpecified;

        private System.DateTime quote_order_dateField;

        private bool quote_order_dateFieldSpecified;

        private decimal quote_order_qtyField;

        private bool quote_order_qtyFieldSpecified;

        private System.DateTime production_order_dateField;

        private bool production_order_dateFieldSpecified;

        private decimal production_order_qtyField;

        private bool production_order_qtyFieldSpecified;

        private System.DateTime preprint_order_dateField;

        private bool preprint_order_dateFieldSpecified;

        private decimal preprint_order_qtyField;

        private bool preprint_order_qtyFieldSpecified;

        private System.DateTime creation_dateField;

        private bool creation_dateFieldSpecified;

        private string user_nameField;

        private System.DateTime last_updated_dateField;

        private bool last_updated_dateFieldSpecified;

        private string last_updated_user_nameField;

        private string erection_methodField;

        private string cust_group_codeField;

        private string boardsField;
        //private decimal boardsField;

        private bool boardsFieldSpecified;

        private string chargeField;
        //private decimal chargeField;

        private bool chargeFieldSpecified;

        private string is_date_change_acceptedField;

        private string no_proofsField;

        private string message_type_codeField;

        private reference_item_type[] reference_itemsField;

        private comment_type[] commentsField;

        private work_centre[] work_centresField;

        private contact[] contactsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int vendor_order_id
        {
            get
            {
                return this.vendor_order_idField;
            }
            set
            {
                this.vendor_order_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tim_status_code
        {
            get
            {
                return this.tim_status_codeField;
            }
            set
            {
                this.tim_status_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tim_status_desc
        {
            get
            {
                return this.tim_status_descField;
            }
            set
            {
                this.tim_status_descField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int parent_vendor_order_id
        {
            get
            {
                return this.parent_vendor_order_idField;
            }
            set
            {
                this.parent_vendor_order_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool parent_vendor_order_idSpecified
        {
            get
            {
                return this.parent_vendor_order_idFieldSpecified;
            }
            set
            {
                this.parent_vendor_order_idFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int tim_asset_id
        {
            get
            {
                return this.tim_asset_idField;
            }
            set
            {
                this.tim_asset_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tim_asset_idSpecified
        {
            get
            {
                return this.tim_asset_idFieldSpecified;
            }
            set
            {
                this.tim_asset_idFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int asset_revision_no
        {
            get
            {
                return this.asset_revision_noField;
            }
            set
            {
                this.asset_revision_noField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool asset_revision_noSpecified
        {
            get
            {
                return this.asset_revision_noFieldSpecified;
            }
            set
            {
                this.asset_revision_noFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tim_asset_code
        {
            get
            {
                return this.tim_asset_codeField;
            }
            set
            {
                this.tim_asset_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tim_asset_desc
        {
            get
            {
                return this.tim_asset_descField;
            }
            set
            {
                this.tim_asset_descField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tim_order_type_code
        {
            get
            {
                return this.tim_order_type_codeField;
            }
            set
            {
                this.tim_order_type_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tim_order_type_desc
        {
            get
            {
                return this.tim_order_type_descField;
            }
            set
            {
                this.tim_order_type_descField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tim_vendor_code
        {
            get
            {
                return this.tim_vendor_codeField;
            }
            set
            {
                this.tim_vendor_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tim_vendor_desc
        {
            get
            {
                return this.tim_vendor_descField;
            }
            set
            {
                this.tim_vendor_descField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string vendor_reference
        {
            get
            {
                return this.vendor_referenceField;
            }
            set
            {
                this.vendor_referenceField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string submitted_user_name
        {
            get
            {
                return this.submitted_user_nameField;
            }
            set
            {
                this.submitted_user_nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime submitted_date
        {
            get
            {
                return this.submitted_dateField;
            }
            set
            {
                this.submitted_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool submitted_dateSpecified
        {
            get
            {
                return this.submitted_dateFieldSpecified;
            }
            set
            {
                this.submitted_dateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        //public System.DateTime actual_due_date
        public string actual_due_date
        {
            get
            {
                return this.actual_due_dateField;
            }
            set
            {
                this.actual_due_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool actual_due_dateSpecified
        {
            get
            {
                return this.actual_due_dateFieldSpecified;
            }
            set
            {
                this.actual_due_dateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime requested_due_date
        {
            get
            {
                return this.requested_due_dateField;
            }
            set
            {
                this.requested_due_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool requested_due_dateSpecified
        {
            get
            {
                return this.requested_due_dateFieldSpecified;
            }
            set
            {
                this.requested_due_dateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime original_due_date
        {
            get
            {
                return this.original_due_dateField;
            }
            set
            {
                this.original_due_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool original_due_dateSpecified
        {
            get
            {
                return this.original_due_dateFieldSpecified;
            }
            set
            {
                this.original_due_dateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool is_completed
        {
            get
            {
                return this.is_completedField;
            }
            set
            {
                this.is_completedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool is_completedSpecified
        {
            get
            {
                return this.is_completedFieldSpecified;
            }
            set
            {
                this.is_completedFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime completed_date
        {
            get
            {
                return this.completed_dateField;
            }
            set
            {
                this.completed_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool completed_dateSpecified
        {
            get
            {
                return this.completed_dateFieldSpecified;
            }
            set
            {
                this.completed_dateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool is_under_review
        {
            get
            {
                return this.is_under_reviewField;
            }
            set
            {
                this.is_under_reviewField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool is_under_reviewSpecified
        {
            get
            {
                return this.is_under_reviewFieldSpecified;
            }
            set
            {
                this.is_under_reviewFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool is_estimate_only
        {
            get
            {
                return this.is_estimate_onlyField;
            }
            set
            {
                this.is_estimate_onlyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool is_estimate_onlySpecified
        {
            get
            {
                return this.is_estimate_onlyFieldSpecified;
            }
            set
            {
                this.is_estimate_onlyFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal estimate_cost
        {
            get
            {
                return this.estimate_costField;
            }
            set
            {
                this.estimate_costField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estimate_costSpecified
        {
            get
            {
                return this.estimate_costFieldSpecified;
            }
            set
            {
                this.estimate_costFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rfq_code
        {
            get
            {
                return this.rfq_codeField;
            }
            set
            {
                this.rfq_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int workflow_id
        {
            get
            {
                return this.workflow_idField;
            }
            set
            {
                this.workflow_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool workflow_idSpecified
        {
            get
            {
                return this.workflow_idFieldSpecified;
            }
            set
            {
                this.workflow_idFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string plant_code
        {
            get
            {
                return this.plant_codeField;
            }
            set
            {
                this.plant_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string plant_desc
        {
            get
            {
                return this.plant_descField;
            }
            set
            {
                this.plant_descField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cost_centre_code
        {
            get
            {
                return this.cost_centre_codeField;
            }
            set
            {
                this.cost_centre_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cost_centre_desc
        {
            get
            {
                return this.cost_centre_descField;
            }
            set
            {
                this.cost_centre_descField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string customer_code
        {
            get
            {
                return this.customer_codeField;
            }
            set
            {
                this.customer_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string customer_desc
        {
            get
            {
                return this.customer_descField;
            }
            set
            {
                this.customer_descField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string product_code
        {
            get
            {
                return this.product_codeField;
            }
            set
            {
                this.product_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string product_desc
        {
            get
            {
                return this.product_descField;
            }
            set
            {
                this.product_descField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int poq_product_id
        {
            get
            {
                return this.poq_product_idField;
            }
            set
            {
                this.poq_product_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool poq_product_idSpecified
        {
            get
            {
                return this.poq_product_idFieldSpecified;
            }
            set
            {
                this.poq_product_idFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int product_id
        {
            get
            {
                return this.product_idField;
            }
            set
            {
                this.product_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool product_idSpecified
        {
            get
            {
                return this.product_idFieldSpecified;
            }
            set
            {
                this.product_idFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int stereo_id
        {
            get
            {
                return this.stereo_idField;
            }
            set
            {
                this.stereo_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool stereo_idSpecified
        {
            get
            {
                return this.stereo_idFieldSpecified;
            }
            set
            {
                this.stereo_idFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string stereo_code
        {
            get
            {
                return this.stereo_codeField;
            }
            set
            {
                this.stereo_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int forme_id
        {
            get
            {
                return this.forme_idField;
            }
            set
            {
                this.forme_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool forme_idSpecified
        {
            get
            {
                return this.forme_idFieldSpecified;
            }
            set
            {
                this.forme_idFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string forme_code
        {
            get
            {
                return this.forme_codeField;
            }
            set
            {
                this.forme_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string board_grade_code
        {
            get
            {
                return this.board_grade_codeField;
            }
            set
            {
                this.board_grade_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string board_grade_desc
        {
            get
            {
                return this.board_grade_descField;
            }
            set
            {
                this.board_grade_descField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string product_style_code
        {
            get
            {
                return this.product_style_codeField;
            }
            set
            {
                this.product_style_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string product_style_desc
        {
            get
            {
                return this.product_style_descField;
            }
            set
            {
                this.product_style_descField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string closure_code
        {
            get
            {
                return this.closure_codeField;
            }
            set
            {
                this.closure_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string closure_desc
        {
            get
            {
                return this.closure_descField;
            }
            set
            {
                this.closure_descField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string drawing_code
        {
            get
            {
                return this.drawing_codeField;
            }
            set
            {
                this.drawing_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int internal_length_mm
        {
            get
            {
                return this.internal_length_mmField;
            }
            set
            {
                this.internal_length_mmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool internal_length_mmSpecified
        {
            get
            {
                return this.internal_length_mmFieldSpecified;
            }
            set
            {
                this.internal_length_mmFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int internal_width_mm
        {
            get
            {
                return this.internal_width_mmField;
            }
            set
            {
                this.internal_width_mmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool internal_width_mmSpecified
        {
            get
            {
                return this.internal_width_mmFieldSpecified;
            }
            set
            {
                this.internal_width_mmFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int internal_depth_mm
        {
            get
            {
                return this.internal_depth_mmField;
            }
            set
            {
                this.internal_depth_mmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool internal_depth_mmSpecified
        {
            get
            {
                return this.internal_depth_mmFieldSpecified;
            }
            set
            {
                this.internal_depth_mmFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public short number_up
        {
            get
            {
                return this.number_upField;
            }
            set
            {
                this.number_upField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool number_upSpecified
        {
            get
            {
                return this.number_upFieldSpecified;
            }
            set
            {
                this.number_upFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ink_code_1
        {
            get
            {
                return this.ink_code_1Field;
            }
            set
            {
                this.ink_code_1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ink_desc_1
        {
            get
            {
                return this.ink_desc_1Field;
            }
            set
            {
                this.ink_desc_1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ink_code_2
        {
            get
            {
                return this.ink_code_2Field;
            }
            set
            {
                this.ink_code_2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ink_desc_2
        {
            get
            {
                return this.ink_desc_2Field;
            }
            set
            {
                this.ink_desc_2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ink_code_3
        {
            get
            {
                return this.ink_code_3Field;
            }
            set
            {
                this.ink_code_3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ink_desc_3
        {
            get
            {
                return this.ink_desc_3Field;
            }
            set
            {
                this.ink_desc_3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ink_code_4
        {
            get
            {
                return this.ink_code_4Field;
            }
            set
            {
                this.ink_code_4Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ink_desc_4
        {
            get
            {
                return this.ink_desc_4Field;
            }
            set
            {
                this.ink_desc_4Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ink_code_5
        {
            get
            {
                return this.ink_code_5Field;
            }
            set
            {
                this.ink_code_5Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ink_desc_5
        {
            get
            {
                return this.ink_desc_5Field;
            }
            set
            {
                this.ink_desc_5Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ink_code_6
        {
            get
            {
                return this.ink_code_6Field;
            }
            set
            {
                this.ink_code_6Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ink_desc_6
        {
            get
            {
                return this.ink_desc_6Field;
            }
            set
            {
                this.ink_desc_6Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string plate_type_code
        {
            get
            {
                return this.plate_type_codeField;
            }
            set
            {
                this.plate_type_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string plate_type_desc
        {
            get
            {
                return this.plate_type_descField;
            }
            set
            {
                this.plate_type_descField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string plate_height_code
        {
            get
            {
                return this.plate_height_codeField;
            }
            set
            {
                this.plate_height_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string plate_height_desc
        {
            get
            {
                return this.plate_height_descField;
            }
            set
            {
                this.plate_height_descField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sbyte no_of_colours
        {
            get
            {
                return this.no_of_coloursField;
            }
            set
            {
                this.no_of_coloursField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool no_of_coloursSpecified
        {
            get
            {
                return this.no_of_coloursFieldSpecified;
            }
            set
            {
                this.no_of_coloursFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool is_preprint
        {
            get
            {
                return this.is_preprintField;
            }
            set
            {
                this.is_preprintField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool is_preprintSpecified
        {
            get
            {
                return this.is_preprintFieldSpecified;
            }
            set
            {
                this.is_preprintFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool is_proof_a3
        {
            get
            {
                return this.is_proof_a3Field;
            }
            set
            {
                this.is_proof_a3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool is_proof_a3Specified
        {
            get
            {
                return this.is_proof_a3FieldSpecified;
            }
            set
            {
                this.is_proof_a3FieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool is_proof_ao_plot
        {
            get
            {
                return this.is_proof_ao_plotField;
            }
            set
            {
                this.is_proof_ao_plotField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool is_proof_ao_plotSpecified
        {
            get
            {
                return this.is_proof_ao_plotFieldSpecified;
            }
            set
            {
                this.is_proof_ao_plotFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool is_proof_pdf
        {
            get
            {
                return this.is_proof_pdfField;
            }
            set
            {
                this.is_proof_pdfField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool is_proof_pdfSpecified
        {
            get
            {
                return this.is_proof_pdfFieldSpecified;
            }
            set
            {
                this.is_proof_pdfFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool is_proof_multiup
        {
            get
            {
                return this.is_proof_multiupField;
            }
            set
            {
                this.is_proof_multiupField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool is_proof_multiupSpecified
        {
            get
            {
                return this.is_proof_multiupFieldSpecified;
            }
            set
            {
                this.is_proof_multiupFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool is_proof_digital
        {
            get
            {
                return this.is_proof_digitalField;
            }
            set
            {
                this.is_proof_digitalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool is_proof_digitalSpecified
        {
            get
            {
                return this.is_proof_digitalFieldSpecified;
            }
            set
            {
                this.is_proof_digitalFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool is_proof_full_deckle
        {
            get
            {
                return this.is_proof_full_deckleField;
            }
            set
            {
                this.is_proof_full_deckleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool is_proof_full_deckleSpecified
        {
            get
            {
                return this.is_proof_full_deckleFieldSpecified;
            }
            set
            {
                this.is_proof_full_deckleFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string screen_ruling_code
        {
            get
            {
                return this.screen_ruling_codeField;
            }
            set
            {
                this.screen_ruling_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string screen_ruling_desc
        {
            get
            {
                return this.screen_ruling_descField;
            }
            set
            {
                this.screen_ruling_descField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string barcode
        {
            get
            {
                return this.barcodeField;
            }
            set
            {
                this.barcodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int barcode_magnification
        {
            get
            {
                return this.barcode_magnificationField;
            }
            set
            {
                this.barcode_magnificationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool barcode_magnificationSpecified
        {
            get
            {
                return this.barcode_magnificationFieldSpecified;
            }
            set
            {
                this.barcode_magnificationFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string bardesc_magnification
        {
            get
            {
                return this.bardesc_magnificationField;
            }
            set
            {
                this.bardesc_magnificationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string barcode_type_code
        {
            get
            {
                return this.barcode_type_codeField;
            }
            set
            {
                this.barcode_type_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cylinder_repeat_code
        {
            get
            {
                return this.cylinder_repeat_codeField;
            }
            set
            {
                this.cylinder_repeat_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cylinder_repeat_desc
        {
            get
            {
                return this.cylinder_repeat_descField;
            }
            set
            {
                this.cylinder_repeat_descField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string artwork_method_code
        {
            get
            {
                return this.artwork_method_codeField;
            }
            set
            {
                this.artwork_method_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string artwork_method_desc
        {
            get
            {
                return this.artwork_method_descField;
            }
            set
            {
                this.artwork_method_descField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string artwork_request_code
        {
            get
            {
                return this.artwork_request_codeField;
            }
            set
            {
                this.artwork_request_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string artwork_request_desc
        {
            get
            {
                return this.artwork_request_descField;
            }
            set
            {
                this.artwork_request_descField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sbyte film_no_up
        {
            get
            {
                return this.film_no_upField;
            }
            set
            {
                this.film_no_upField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool film_no_upSpecified
        {
            get
            {
                return this.film_no_upFieldSpecified;
            }
            set
            {
                this.film_no_upFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sbyte no_cartons_across
        {
            get
            {
                return this.no_cartons_acrossField;
            }
            set
            {
                this.no_cartons_acrossField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool no_cartons_acrossSpecified
        {
            get
            {
                return this.no_cartons_acrossFieldSpecified;
            }
            set
            {
                this.no_cartons_acrossFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public sbyte no_cartons_around
        {
            get
            {
                return this.no_cartons_aroundField;
            }
            set
            {
                this.no_cartons_aroundField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool no_cartons_aroundSpecified
        {
            get
            {
                return this.no_cartons_aroundFieldSpecified;
            }
            set
            {
                this.no_cartons_aroundFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string preprint_code
        {
            get
            {
                return this.preprint_codeField;
            }
            set
            {
                this.preprint_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string preprint_desc
        {
            get
            {
                return this.preprint_descField;
            }
            set
            {
                this.preprint_descField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string film_comment
        {
            get
            {
                return this.film_commentField;
            }
            set
            {
                this.film_commentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal total_cost
        {
            get
            {
                return this.total_costField;
            }
            set
            {
                this.total_costField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool total_costSpecified
        {
            get
            {
                return this.total_costFieldSpecified;
            }
            set
            {
                this.total_costFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        //[XmlElement(IsNullable = true)]
        //public decimal total_hours
        public string total_hours
        {
            get
            {
                return this.total_hoursField;
            }
            set
            {
                this.total_hoursField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool total_hoursSpecified
        {
            get
            {
                return this.total_hoursFieldSpecified;
            }
            set
            {
                this.total_hoursFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        //public decimal sqm
        public string sqm
        {
            get
            {
                return this.sqmField;
            }
            set
            {
                this.sqmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sqmSpecified
        {
            get
            {
                return this.sqmFieldSpecified;
            }
            set
            {
                this.sqmFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime quote_order_date
        {
            get
            {
                return this.quote_order_dateField;
            }
            set
            {
                this.quote_order_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quote_order_dateSpecified
        {
            get
            {
                return this.quote_order_dateFieldSpecified;
            }
            set
            {
                this.quote_order_dateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal quote_order_qty
        {
            get
            {
                return this.quote_order_qtyField;
            }
            set
            {
                this.quote_order_qtyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool quote_order_qtySpecified
        {
            get
            {
                return this.quote_order_qtyFieldSpecified;
            }
            set
            {
                this.quote_order_qtyFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime production_order_date
        {
            get
            {
                return this.production_order_dateField;
            }
            set
            {
                this.production_order_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool production_order_dateSpecified
        {
            get
            {
                return this.production_order_dateFieldSpecified;
            }
            set
            {
                this.production_order_dateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal production_order_qty
        {
            get
            {
                return this.production_order_qtyField;
            }
            set
            {
                this.production_order_qtyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool production_order_qtySpecified
        {
            get
            {
                return this.production_order_qtyFieldSpecified;
            }
            set
            {
                this.production_order_qtyFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime preprint_order_date
        {
            get
            {
                return this.preprint_order_dateField;
            }
            set
            {
                this.preprint_order_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool preprint_order_dateSpecified
        {
            get
            {
                return this.preprint_order_dateFieldSpecified;
            }
            set
            {
                this.preprint_order_dateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal preprint_order_qty
        {
            get
            {
                return this.preprint_order_qtyField;
            }
            set
            {
                this.preprint_order_qtyField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool preprint_order_qtySpecified
        {
            get
            {
                return this.preprint_order_qtyFieldSpecified;
            }
            set
            {
                this.preprint_order_qtyFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime creation_date
        {
            get
            {
                return this.creation_dateField;
            }
            set
            {
                this.creation_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creation_dateSpecified
        {
            get
            {
                return this.creation_dateFieldSpecified;
            }
            set
            {
                this.creation_dateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user_name
        {
            get
            {
                return this.user_nameField;
            }
            set
            {
                this.user_nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime last_updated_date
        {
            get
            {
                return this.last_updated_dateField;
            }
            set
            {
                this.last_updated_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool last_updated_dateSpecified
        {
            get
            {
                return this.last_updated_dateFieldSpecified;
            }
            set
            {
                this.last_updated_dateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string last_updated_user_name
        {
            get
            {
                return this.last_updated_user_nameField;
            }
            set
            {
                this.last_updated_user_nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string erection_method
        {
            get
            {
                return this.erection_methodField;
            }
            set
            {
                this.erection_methodField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cust_group_code
        {
            get
            {
                return this.cust_group_codeField;
            }
            set
            {
                this.cust_group_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        //public decimal boards        
        public string boards
        {
            get
            {
                return this.boardsField;
            }
            set
            {
                this.boardsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool boardsSpecified
        {
            get
            {
                return this.boardsFieldSpecified;
            }
            set
            {
                this.boardsFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        //public decimal charge
        public string charge
        {
            get
            {
                return this.chargeField;
            }
            set
            {
                this.chargeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool chargeSpecified
        {
            get
            {
                return this.chargeFieldSpecified;
            }
            set
            {
                this.chargeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string is_date_change_accepted
        {
            get
            {
                return this.is_date_change_acceptedField;
            }
            set
            {
                this.is_date_change_acceptedField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string no_proofs
        {
            get
            {
                return this.no_proofsField;
            }
            set
            {
                this.no_proofsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message_type_code
        {
            get
            {
                return this.message_type_codeField;
            }
            set
            {
                this.message_type_codeField = value;
            }
        }


        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("reference_item", IsNullable = false)]
        public reference_item_type[] reference_items
        {
            get
            {
                return this.reference_itemsField;
            }
            set
            {
                this.reference_itemsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("comment", IsNullable = false)]
        public comment_type[] comments
        {
            get
            {
                return this.commentsField;
            }
            set
            {
                this.commentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("work_centre", IsNullable = false)]
        public work_centre[] work_centres
        {
            get
            {
                return this.work_centresField;
            }
            set
            {
                this.work_centresField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("contact", IsNullable = false)]
        public contact[] contacts
        {
            get
            {
                return this.contactsField;
            }
            set
            {
                this.contactsField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Visy.ECommerce.TIM.Schemas/datatypes")]
    [System.Xml.Serialization.XmlRootAttribute("reference_item", Namespace = "http://Visy.ECommerce.TIM.Schemas/datatypes", IsNullable = false)]
    public partial class reference_item_type
    {

        private int sequence_noField;

        private bool sequence_noFieldSpecified;

        private int tim_reference_item_idField;

        private int attachment_item_idField;

        private bool attachment_item_idFieldSpecified;

        private string file_pathField;

        private string file_nameField;

        private string zip_file_pathField;

        private string source_codeField;

        private string descriptionField;

        private int sizeField;

        private bool sizeFieldSpecified;

        private System.DateTime creation_dateField;

        private bool creation_dateFieldSpecified;

        private string user_nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int sequence_no
        {
            get
            {
                return this.sequence_noField;
            }
            set
            {
                this.sequence_noField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sequence_noSpecified
        {
            get
            {
                return this.sequence_noFieldSpecified;
            }
            set
            {
                this.sequence_noFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int tim_reference_item_id
        {
            get
            {
                return this.tim_reference_item_idField;
            }
            set
            {
                this.tim_reference_item_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int attachment_item_id
        {
            get
            {
                return this.attachment_item_idField;
            }
            set
            {
                this.attachment_item_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool attachment_item_idSpecified
        {
            get
            {
                return this.attachment_item_idFieldSpecified;
            }
            set
            {
                this.attachment_item_idFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string file_path
        {
            get
            {
                return this.file_pathField;
            }
            set
            {
                this.file_pathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string file_name
        {
            get
            {
                return this.file_nameField;
            }
            set
            {
                this.file_nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string zip_file_path
        {
            get
            {
                return this.zip_file_pathField;
            }
            set
            {
                this.zip_file_pathField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string source_code
        {
            get
            {
                return this.source_codeField;
            }
            set
            {
                this.source_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int size
        {
            get
            {
                return this.sizeField;
            }
            set
            {
                this.sizeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sizeSpecified
        {
            get
            {
                return this.sizeFieldSpecified;
            }
            set
            {
                this.sizeFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime creation_date
        {
            get
            {
                return this.creation_dateField;
            }
            set
            {
                this.creation_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creation_dateSpecified
        {
            get
            {
                return this.creation_dateFieldSpecified;
            }
            set
            {
                this.creation_dateFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user_name
        {
            get
            {
                return this.user_nameField;
            }
            set
            {
                this.user_nameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://Visy.ECommerce.TIM.Schemas/datatypes")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://Visy.ECommerce.TIM.Schemas/datatypes", IsNullable = false)]
    public partial class work_centre
    {

        private int sequence_noField;

        private bool sequence_noFieldSpecified;

        private string work_centre_codeField;

        private string work_centre_descField;

        private bool is_corrugatorField;

        private bool is_corrugatorFieldSpecified;

        private bool is_finisherField;

        private bool is_finisherFieldSpecified;

        private bool is_gluerField;

        private bool is_gluerFieldSpecified;

        private bool is_strapperField;

        private bool is_strapperFieldSpecified;

        private bool is_slitterField;

        private bool is_slitterFieldSpecified;

        private int sheet_length_mmField;

        private bool sheet_length_mmFieldSpecified;

        private int sheet_width_mmField;

        private bool sheet_width_mmFieldSpecified;

        private int number_up_lengthField;

        private bool number_up_lengthFieldSpecified;

        private int number_up_widthField;

        private bool number_up_widthFieldSpecified;

        private int crease_position_1Field;

        private bool crease_position_1FieldSpecified;

        private int crease_position_2Field;

        private bool crease_position_2FieldSpecified;

        private int crease_position_3Field;

        private bool crease_position_3FieldSpecified;

        private int crease_position_4Field;

        private bool crease_position_4FieldSpecified;

        private int crease_position_5Field;

        private bool crease_position_5FieldSpecified;

        private int crease_position_6Field;

        private bool crease_position_6FieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int sequence_no
        {
            get
            {
                return this.sequence_noField;
            }
            set
            {
                this.sequence_noField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sequence_noSpecified
        {
            get
            {
                return this.sequence_noFieldSpecified;
            }
            set
            {
                this.sequence_noFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string work_centre_code
        {
            get
            {
                return this.work_centre_codeField;
            }
            set
            {
                this.work_centre_codeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string work_centre_desc
        {
            get
            {
                return this.work_centre_descField;
            }
            set
            {
                this.work_centre_descField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool is_corrugator
        {
            get
            {
                return this.is_corrugatorField;
            }
            set
            {
                this.is_corrugatorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool is_corrugatorSpecified
        {
            get
            {
                return this.is_corrugatorFieldSpecified;
            }
            set
            {
                this.is_corrugatorFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool is_finisher
        {
            get
            {
                return this.is_finisherField;
            }
            set
            {
                this.is_finisherField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool is_finisherSpecified
        {
            get
            {
                return this.is_finisherFieldSpecified;
            }
            set
            {
                this.is_finisherFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool is_gluer
        {
            get
            {
                return this.is_gluerField;
            }
            set
            {
                this.is_gluerField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool is_gluerSpecified
        {
            get
            {
                return this.is_gluerFieldSpecified;
            }
            set
            {
                this.is_gluerFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool is_strapper
        {
            get
            {
                return this.is_strapperField;
            }
            set
            {
                this.is_strapperField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool is_strapperSpecified
        {
            get
            {
                return this.is_strapperFieldSpecified;
            }
            set
            {
                this.is_strapperFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool is_slitter
        {
            get
            {
                return this.is_slitterField;
            }
            set
            {
                this.is_slitterField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool is_slitterSpecified
        {
            get
            {
                return this.is_slitterFieldSpecified;
            }
            set
            {
                this.is_slitterFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int sheet_length_mm
        {
            get
            {
                return this.sheet_length_mmField;
            }
            set
            {
                this.sheet_length_mmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sheet_length_mmSpecified
        {
            get
            {
                return this.sheet_length_mmFieldSpecified;
            }
            set
            {
                this.sheet_length_mmFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int sheet_width_mm
        {
            get
            {
                return this.sheet_width_mmField;
            }
            set
            {
                this.sheet_width_mmField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sheet_width_mmSpecified
        {
            get
            {
                return this.sheet_width_mmFieldSpecified;
            }
            set
            {
                this.sheet_width_mmFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int number_up_length
        {
            get
            {
                return this.number_up_lengthField;
            }
            set
            {
                this.number_up_lengthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool number_up_lengthSpecified
        {
            get
            {
                return this.number_up_lengthFieldSpecified;
            }
            set
            {
                this.number_up_lengthFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int number_up_width
        {
            get
            {
                return this.number_up_widthField;
            }
            set
            {
                this.number_up_widthField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool number_up_widthSpecified
        {
            get
            {
                return this.number_up_widthFieldSpecified;
            }
            set
            {
                this.number_up_widthFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int crease_position_1
        {
            get
            {
                return this.crease_position_1Field;
            }
            set
            {
                this.crease_position_1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool crease_position_1Specified
        {
            get
            {
                return this.crease_position_1FieldSpecified;
            }
            set
            {
                this.crease_position_1FieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int crease_position_2
        {
            get
            {
                return this.crease_position_2Field;
            }
            set
            {
                this.crease_position_2Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool crease_position_2Specified
        {
            get
            {
                return this.crease_position_2FieldSpecified;
            }
            set
            {
                this.crease_position_2FieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int crease_position_3
        {
            get
            {
                return this.crease_position_3Field;
            }
            set
            {
                this.crease_position_3Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool crease_position_3Specified
        {
            get
            {
                return this.crease_position_3FieldSpecified;
            }
            set
            {
                this.crease_position_3FieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int crease_position_4
        {
            get
            {
                return this.crease_position_4Field;
            }
            set
            {
                this.crease_position_4Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool crease_position_4Specified
        {
            get
            {
                return this.crease_position_4FieldSpecified;
            }
            set
            {
                this.crease_position_4FieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int crease_position_5
        {
            get
            {
                return this.crease_position_5Field;
            }
            set
            {
                this.crease_position_5Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool crease_position_5Specified
        {
            get
            {
                return this.crease_position_5FieldSpecified;
            }
            set
            {
                this.crease_position_5FieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int crease_position_6
        {
            get
            {
                return this.crease_position_6Field;
            }
            set
            {
                this.crease_position_6Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool crease_position_6Specified
        {
            get
            {
                return this.crease_position_6FieldSpecified;
            }
            set
            {
                this.crease_position_6FieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://Visy.ECommerce.TIM.Schemas/datatypes")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://Visy.ECommerce.TIM.Schemas/datatypes", IsNullable = false)]
    public partial class contact
    {

        private int sequence_noField;

        private bool sequence_noFieldSpecified;

        private string typeField;

        private string nameField;

        private string phoneField;

        private string emailField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int sequence_no
        {
            get
            {
                return this.sequence_noField;
            }
            set
            {
                this.sequence_noField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sequence_noSpecified
        {
            get
            {
                return this.sequence_noFieldSpecified;
            }
            set
            {
                this.sequence_noFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://Visy.ECommerce.TIM.Schemas/datatypes")]
    [System.Xml.Serialization.XmlRootAttribute("comment", Namespace = "http://Visy.ECommerce.TIM.Schemas/datatypes", IsNullable = false)]
    public partial class comment_type
    {

        private int sequence_noField;

        private bool sequence_noFieldSpecified;

        //private int tim_comment_idField;
        private string tim_comment_idField;

        private string commentField;

        private string user_nameField;

        private System.DateTime creation_dateField;

        private bool creation_dateFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int sequence_no
        {
            get
            {
                return this.sequence_noField;
            }
            set
            {
                this.sequence_noField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool sequence_noSpecified
        {
            get
            {
                return this.sequence_noFieldSpecified;
            }
            set
            {
                this.sequence_noFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        //public int tim_comment_id
        public string tim_comment_id
        {
            get
            {
                return this.tim_comment_idField;
            }
            set
            {
                this.tim_comment_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string comment
        {
            get
            {
                return this.commentField;
            }
            set
            {
                this.commentField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user_name
        {
            get
            {
                return this.user_nameField;
            }
            set
            {
                this.user_nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime creation_date
        {
            get
            {
                return this.creation_dateField;
            }
            set
            {
                this.creation_dateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool creation_dateSpecified
        {
            get
            {
                return this.creation_dateFieldSpecified;
            }
            set
            {
                this.creation_dateFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://Visy.ECommerce.TIM.Schemas")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://Visy.ECommerce.TIM.Schemas", IsNullable = false)]
    public partial class accept_order
    {

        private vendor_order_type vendor_orderField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://Visy.ECommerce.TIM.Schemas/datatypes")]
        public vendor_order_type vendor_order
        {
            get
            {
                return this.vendor_orderField;
            }
            set
            {
                this.vendor_orderField = value;
            }
        }
    }
}