//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 

namespace Visy.Middleware.LGX.TIM.Components
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://Middleware.LGX.ActiveOrderSyncResponse")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://Middleware.LGX.ActiveOrderSyncResponse", IsNullable = false)]
    public partial class ActiveOrderSyncResponse
    {

        private ActiveOrderSyncResponseOrders[] ordersField;

        private string tim_vendor_codeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Orders", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ActiveOrderSyncResponseOrders[] Orders
        {
            get
            {
                return this.ordersField;
            }
            set
            {
                this.ordersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tim_vendor_code
        {
            get
            {
                return this.tim_vendor_codeField;
            }
            set
            {
                this.tim_vendor_codeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://NewTIMTest.ActiveOrderSyncResponse")]
    public partial class ActiveOrderSyncResponseOrders
    {

        //private int tim_vendor_order_idField;
        private string tim_vendor_order_idField;

        private string messageField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string tim_vendor_order_id
        {
            get
            {
                return this.tim_vendor_order_idField;
            }
            set
            {
                this.tim_vendor_order_idField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
}