//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 
namespace Visy.Middleware.LGX.TIM.Components
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://Visy.ECommerce.TIM.Schemas")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://Visy.ECommerce.TIM.Schemas", IsNullable = false)]
    //[System.Xml.Serialization.XmlRootAttribute("vendor_order", Namespace = "http://Visy.ECommerce.TIM.Schemas/datatypes", IsNullable = false)]
    public partial class complete_order
    {

        private vendor_order_type vendor_orderField;

        private vendor_order_type message_type_codeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://Visy.ECommerce.TIM.Schemas/datatypes")]
        public vendor_order_type vendor_order
        {
            get
            {
                return this.vendor_orderField;
            }
            set
            {
                this.vendor_orderField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://Visy.ECommerce.TIM.Schemas/datatypes")]
        public vendor_order_type message_type_code
        {
            get
            {
                return this.message_type_codeField;
            }
            set
            {
                this.message_type_codeField = value;
            }
        }
    }
}