//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace= "http://Visy.Middleware.SAP.GSGlobal.Schemas.SinglePOASN", IsNullable=false)]
public partial class SinglePOASN {
    
    private string pONoField;
    
    private SinglePOASNDetail[] detailField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PONo {
        get {
            return this.pONoField;
        }
        set {
            this.pONoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Detail", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SinglePOASNDetail[] Detail {
        get {
            return this.detailField;
        }
        set {
            this.detailField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SinglePOASNDetail {
    
    private string visyPOEntNoField;

    public void CreateBatch(int NoOfBatches)
    {
        this.BatchItem = new SinglePOASNDetailBatchItem[NoOfBatches];
    }
    
    
    private SinglePOASNDetailBatchItem[] batchItemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VisyPOEntNo {
        get {
            return this.visyPOEntNoField;
        }
        set {
            this.visyPOEntNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BatchItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public SinglePOASNDetailBatchItem[] BatchItem {
        get {
            return this.batchItemField;
        }
        set {
            this.batchItemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SinglePOASNDetailBatchItem {
    
    private string lineNoField;
    
    private string productCodeField;
    
    private string invoiceNoField;
    
    private string fileNoField;
    
    private string inspectionNoField;
    
    private string packageNoField;
    
    private string temperField;
    
    private string sizeField;
    
    private string coatingField;
    
    private string footageField;
    
    private string netWeightField;
    
    private string grossWeightField;
    
    private string eTDField;
    
    private string eTAField;
    
    private string vesselField;
    
    private string destinationPortField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LineNo {
        get {
            return this.lineNoField;
        }
        set {
            this.lineNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ProductCode {
        get {
            return this.productCodeField;
        }
        set {
            this.productCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InvoiceNo {
        get {
            return this.invoiceNoField;
        }
        set {
            this.invoiceNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FileNo {
        get {
            return this.fileNoField;
        }
        set {
            this.fileNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InspectionNo {
        get {
            return this.inspectionNoField;
        }
        set {
            this.inspectionNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PackageNo {
        get {
            return this.packageNoField;
        }
        set {
            this.packageNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Temper {
        get {
            return this.temperField;
        }
        set {
            this.temperField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Size {
        get {
            return this.sizeField;
        }
        set {
            this.sizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Coating {
        get {
            return this.coatingField;
        }
        set {
            this.coatingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Footage {
        get {
            return this.footageField;
        }
        set {
            this.footageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NetWeight {
        get {
            return this.netWeightField;
        }
        set {
            this.netWeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GrossWeight {
        get {
            return this.grossWeightField;
        }
        set {
            this.grossWeightField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ETD {
        get {
            return this.eTDField;
        }
        set {
            this.eTDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ETA {
        get {
            return this.eTAField;
        }
        set {
            this.eTAField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Vessel {
        get {
            return this.vesselField;
        }
        set {
            this.vesselField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DestinationPort {
        get {
            return this.destinationPortField;
        }
        set {
            this.destinationPortField = value;
        }
    }
}
