//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Visy.Middleware.Common.Schemas.LGX.ORDER")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://Visy.Middleware.Common.Schemas.LGX.ORDER", IsNullable=false)]
public partial class ORDER {
    
    private Header headerField;
    
    private Text textField;
    
    private Detail[] detailField;
    
    private Summary summaryField;
    
    /// <remarks/>
    public Header Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    public Text Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Detail")]
    public Detail[] Detail {
        get {
            return this.detailField;
        }
        set {
            this.detailField = value;
        }
    }
    
    /// <remarks/>
    public Summary Summary {
        get {
            return this.summaryField;
        }
        set {
            this.summaryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Visy.Middleware.Common.Schemas.LGX.ORDER")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://Visy.Middleware.Common.Schemas.LGX.ORDER", IsNullable=false)]
public partial class Header {
    
    private string order_typeField;
    
    private string application_codeField;
    
    private string customer_eanField;
    
    private string plant_codeField;
    
    private string customer_codeField;
    
    private string purchase_order_numberField;
    
    private string purchase_order_dateField;
    
    private System.DateTime purchase_order_timeField;
    
    private bool purchase_order_timeFieldSpecified;
    
    private string customer_nameField;
    
    private string customer_addressField;
    
    private string contact_nameField;
    
    private string contact_departmentField;
    
    private string contact_numberField;
    
    private string biztalk_idField;
    
    private string acknowledge_documentField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string order_type {
        get {
            return this.order_typeField;
        }
        set {
            this.order_typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string application_code {
        get {
            return this.application_codeField;
        }
        set {
            this.application_codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string customer_ean {
        get {
            return this.customer_eanField;
        }
        set {
            this.customer_eanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string plant_code {
        get {
            return this.plant_codeField;
        }
        set {
            this.plant_codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string customer_code {
        get {
            return this.customer_codeField;
        }
        set {
            this.customer_codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string purchase_order_number {
        get {
            return this.purchase_order_numberField;
        }
        set {
            this.purchase_order_numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string purchase_order_date {
        get {
            return this.purchase_order_dateField;
        }
        set {
            this.purchase_order_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="time")]
    public System.DateTime purchase_order_time {
        get {
            return this.purchase_order_timeField;
        }
        set {
            this.purchase_order_timeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool purchase_order_timeSpecified {
        get {
            return this.purchase_order_timeFieldSpecified;
        }
        set {
            this.purchase_order_timeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string customer_name {
        get {
            return this.customer_nameField;
        }
        set {
            this.customer_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string customer_address {
        get {
            return this.customer_addressField;
        }
        set {
            this.customer_addressField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string contact_name {
        get {
            return this.contact_nameField;
        }
        set {
            this.contact_nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string contact_department {
        get {
            return this.contact_departmentField;
        }
        set {
            this.contact_departmentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string contact_number {
        get {
            return this.contact_numberField;
        }
        set {
            this.contact_numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string biztalk_id {
        get {
            return this.biztalk_idField;
        }
        set {
            this.biztalk_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string acknowledge_document {
        get {
            return this.acknowledge_documentField;
        }
        set {
            this.acknowledge_documentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Visy.Middleware.Common.Schemas.LGX.ORDER")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://Visy.Middleware.Common.Schemas.LGX.ORDER", IsNullable=false)]
public partial class Text {
    
    private string text_1Field;
    
    private string text_2Field;
    
    private string text_3Field;
    
    private string text_4Field;
    
    private string text_5Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string text_1 {
        get {
            return this.text_1Field;
        }
        set {
            this.text_1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string text_2 {
        get {
            return this.text_2Field;
        }
        set {
            this.text_2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string text_3 {
        get {
            return this.text_3Field;
        }
        set {
            this.text_3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string text_4 {
        get {
            return this.text_4Field;
        }
        set {
            this.text_4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string text_5 {
        get {
            return this.text_5Field;
        }
        set {
            this.text_5Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Visy.Middleware.Common.Schemas.LGX.ORDER")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://Visy.Middleware.Common.Schemas.LGX.ORDER", IsNullable=false)]
public partial class Detail {
    
    private string line_indicatorField;
    
    private float line_numberField;
    
    private string factord_idField;
    
    private string product_codeField;
    
    private float quantityField;
    
    private bool quantityFieldSpecified;
    
    private string unit_of_measureField;
    
    private float price_excluding_taxField;
    
    private bool price_excluding_taxFieldSpecified;
    
    private string delivery_dateField;
    
    private string delivery_timeField;
    
    private string address_idField;
    
    private string warehouse_codeField;
    
    private string commentField;
    
    private string custord_detail_timestampField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string line_indicator {
        get {
            return this.line_indicatorField;
        }
        set {
            this.line_indicatorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float line_number {
        get {
            return this.line_numberField;
        }
        set {
            this.line_numberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string factord_id {
        get {
            return this.factord_idField;
        }
        set {
            this.factord_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string product_code {
        get {
            return this.product_codeField;
        }
        set {
            this.product_codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool quantitySpecified {
        get {
            return this.quantityFieldSpecified;
        }
        set {
            this.quantityFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unit_of_measure {
        get {
            return this.unit_of_measureField;
        }
        set {
            this.unit_of_measureField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float price_excluding_tax {
        get {
            return this.price_excluding_taxField;
        }
        set {
            this.price_excluding_taxField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool price_excluding_taxSpecified {
        get {
            return this.price_excluding_taxFieldSpecified;
        }
        set {
            this.price_excluding_taxFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string delivery_date {
        get {
            return this.delivery_dateField;
        }
        set {
            this.delivery_dateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string delivery_time {
        get {
            return this.delivery_timeField;
        }
        set {
            this.delivery_timeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string address_id {
        get {
            return this.address_idField;
        }
        set {
            this.address_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string warehouse_code {
        get {
            return this.warehouse_codeField;
        }
        set {
            this.warehouse_codeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string custord_detail_timestamp {
        get {
            return this.custord_detail_timestampField;
        }
        set {
            this.custord_detail_timestampField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Visy.Middleware.Common.Schemas.LGX.ORDER")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://Visy.Middleware.Common.Schemas.LGX.ORDER", IsNullable=false)]
public partial class Summary {
    
    private float total_order_quantityField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public float total_order_quantity {
        get {
            return this.total_order_quantityField;
        }
        set {
            this.total_order_quantityField = value;
        }
    }
}
