//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.42.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Visy.Middleware.SAP.NipponSteel.NIPPONSTEEL_FF")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://Visy.Middleware.SAP.NipponSteel.NIPPONSTEEL_FF", IsNullable=false)]
public partial class Order {
    
    private OrderHeader headerField;
    
    private OrderOrderLine[] orderLineField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public OrderHeader Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OrderLine", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public OrderOrderLine[] OrderLine {
        get {
            return this.orderLineField;
        }
        set {
            this.orderLineField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Visy.Middleware.SAP.NipponSteel.NIPPONSTEEL_FF")]
public partial class OrderHeader {
    
    private string customerField;
    
    private string manufacturerField;
    
    private string commidityField;
    
    private string lineNoField;
    
    private string sizeField;
    
    private string thicknessField;
    
    private string widthField;
    
    private string specificationField;
    
    private string coatingField;
    
    private string finishField;
    
    private string customerCtrlField;
    
    private string pONoField;
    
    private string pOBodyField;
    
    private string contractNoField;
    
    private string invoiceNoField;
    
    private string vesselNameField;
    
    private string voyageNoField;
    
    private string eTAGeelongField;
    
    private string certificateNoField;
    
    private string caseNoField;
    
    private string inspectionNoField;
    
    private string castNoField;
    
    private string coilNoField;
    
    private string quantityField;
    
    private string netMassKGField;
    
    private string netMassMTField;
    
    private string grossMassKGField;
    
    private string grossMassMTField;
    
    private string productDateField;
    
    private string nSCRefNoField;
    
    private string nSCRefNo2Field;
    
    private string misoInvoiceNoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Customer {
        get {
            return this.customerField;
        }
        set {
            this.customerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Manufacturer {
        get {
            return this.manufacturerField;
        }
        set {
            this.manufacturerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Commidity {
        get {
            return this.commidityField;
        }
        set {
            this.commidityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LineNo {
        get {
            return this.lineNoField;
        }
        set {
            this.lineNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Size {
        get {
            return this.sizeField;
        }
        set {
            this.sizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Thickness {
        get {
            return this.thicknessField;
        }
        set {
            this.thicknessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Specification {
        get {
            return this.specificationField;
        }
        set {
            this.specificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Coating {
        get {
            return this.coatingField;
        }
        set {
            this.coatingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Finish {
        get {
            return this.finishField;
        }
        set {
            this.finishField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerCtrl {
        get {
            return this.customerCtrlField;
        }
        set {
            this.customerCtrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PONo {
        get {
            return this.pONoField;
        }
        set {
            this.pONoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string POBody {
        get {
            return this.pOBodyField;
        }
        set {
            this.pOBodyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ContractNo {
        get {
            return this.contractNoField;
        }
        set {
            this.contractNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InvoiceNo {
        get {
            return this.invoiceNoField;
        }
        set {
            this.invoiceNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VesselName {
        get {
            return this.vesselNameField;
        }
        set {
            this.vesselNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VoyageNo {
        get {
            return this.voyageNoField;
        }
        set {
            this.voyageNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ETAGeelong {
        get {
            return this.eTAGeelongField;
        }
        set {
            this.eTAGeelongField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CertificateNo {
        get {
            return this.certificateNoField;
        }
        set {
            this.certificateNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CaseNo {
        get {
            return this.caseNoField;
        }
        set {
            this.caseNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InspectionNo {
        get {
            return this.inspectionNoField;
        }
        set {
            this.inspectionNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CastNo {
        get {
            return this.castNoField;
        }
        set {
            this.castNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CoilNo {
        get {
            return this.coilNoField;
        }
        set {
            this.coilNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NetMassKG {
        get {
            return this.netMassKGField;
        }
        set {
            this.netMassKGField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NetMassMT {
        get {
            return this.netMassMTField;
        }
        set {
            this.netMassMTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GrossMassKG {
        get {
            return this.grossMassKGField;
        }
        set {
            this.grossMassKGField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GrossMassMT {
        get {
            return this.grossMassMTField;
        }
        set {
            this.grossMassMTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ProductDate {
        get {
            return this.productDateField;
        }
        set {
            this.productDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NSCRefNo {
        get {
            return this.nSCRefNoField;
        }
        set {
            this.nSCRefNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NSCRefNo2 {
        get {
            return this.nSCRefNo2Field;
        }
        set {
            this.nSCRefNo2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MisoInvoiceNo {
        get {
            return this.misoInvoiceNoField;
        }
        set {
            this.misoInvoiceNoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.42")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Visy.Middleware.SAP.NipponSteel.NIPPONSTEEL_FF")]
public partial class OrderOrderLine {
    
    private string customerField;
    
    private string manufacturerField;
    
    private string commodityField;
    
    private string lineNoField;
    
    private string sizeField;
    
    private string thicknessField;
    
    private string widthField;
    
    private string specificationField;
    
    private string coatingField;
    
    private string finishField;
    
    private string customerCtrlField;
    
    private string pONoField;
    
    private string pONoBodyField;
    
    private string contractNoField;
    
    private string invoiceNoField;
    
    private string vessselNameField;
    
    private string voyageNoField;
    
    private string eTAGeelongField;
    
    private string certificateNoField;
    
    private string caseNoField;
    
    private string inspectionNoField;
    
    private string castNoField;
    
    private string coilNoField;
    
    private string quantityField;
    
    private string netMassKGField;
    
    private string netMassMTField;
    
    private string grossMassKGField;
    
    private string grossMassMTField;
    
    private string productDateField;
    
    private string nSCRefNoField;
    
    private string nSCRefNo2Field;
    
    private string misoInvoiceNoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Customer {
        get {
            return this.customerField;
        }
        set {
            this.customerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Manufacturer {
        get {
            return this.manufacturerField;
        }
        set {
            this.manufacturerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Commodity {
        get {
            return this.commodityField;
        }
        set {
            this.commodityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LineNo {
        get {
            return this.lineNoField;
        }
        set {
            this.lineNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Size {
        get {
            return this.sizeField;
        }
        set {
            this.sizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Thickness {
        get {
            return this.thicknessField;
        }
        set {
            this.thicknessField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Width {
        get {
            return this.widthField;
        }
        set {
            this.widthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Specification {
        get {
            return this.specificationField;
        }
        set {
            this.specificationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Coating {
        get {
            return this.coatingField;
        }
        set {
            this.coatingField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Finish {
        get {
            return this.finishField;
        }
        set {
            this.finishField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CustomerCtrl {
        get {
            return this.customerCtrlField;
        }
        set {
            this.customerCtrlField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PONo {
        get {
            return this.pONoField;
        }
        set {
            this.pONoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PONoBody {
        get {
            return this.pONoBodyField;
        }
        set {
            this.pONoBodyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ContractNo {
        get {
            return this.contractNoField;
        }
        set {
            this.contractNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InvoiceNo {
        get {
            return this.invoiceNoField;
        }
        set {
            this.invoiceNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VessselName {
        get {
            return this.vessselNameField;
        }
        set {
            this.vessselNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string VoyageNo {
        get {
            return this.voyageNoField;
        }
        set {
            this.voyageNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ETAGeelong {
        get {
            return this.eTAGeelongField;
        }
        set {
            this.eTAGeelongField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CertificateNo {
        get {
            return this.certificateNoField;
        }
        set {
            this.certificateNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CaseNo {
        get {
            return this.caseNoField;
        }
        set {
            this.caseNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InspectionNo {
        get {
            return this.inspectionNoField;
        }
        set {
            this.inspectionNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CastNo {
        get {
            return this.castNoField;
        }
        set {
            this.castNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CoilNo {
        get {
            return this.coilNoField;
        }
        set {
            this.coilNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NetMassKG {
        get {
            return this.netMassKGField;
        }
        set {
            this.netMassKGField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NetMassMT {
        get {
            return this.netMassMTField;
        }
        set {
            this.netMassMTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GrossMassKG {
        get {
            return this.grossMassKGField;
        }
        set {
            this.grossMassKGField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GrossMassMT {
        get {
            return this.grossMassMTField;
        }
        set {
            this.grossMassMTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ProductDate {
        get {
            return this.productDateField;
        }
        set {
            this.productDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NSCRefNo {
        get {
            return this.nSCRefNoField;
        }
        set {
            this.nSCRefNoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NSCRefNo2 {
        get {
            return this.nSCRefNo2Field;
        }
        set {
            this.nSCRefNo2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MisoInvoiceNo {
        get {
            return this.misoInvoiceNoField;
        }
        set {
            this.misoInvoiceNoField = value;
        }
    }
}
